import type { WatchlistInsight, WatchlistTermReview } from "@/domain/types";

interface WatchlistReviewPromptInput {
  channelTitle: string;
  videoTitle: string;
  topic: string;
  transcript: string;
  terms: WatchlistTermReview[];
  priorInsights: WatchlistInsight[];
  language: string;
}

export function buildWatchlistReviewPrompt({
  channelTitle,
  videoTitle,
  topic,
  transcript,
  terms,
  priorInsights,
  language,
}: WatchlistReviewPromptInput): string {
  const history = priorInsights.slice(0, 8).map((insight) => ({
    claims: insight.claims.map((claim) => claim.text),
    signals: (insight.signals ?? []).map((signal) => ({ claim: signal.claim, type: signal.signalType })),
    positions: insight.positionChanges.map((change) => ({ topic: change.topic, position: change.currentPosition })),
  }));

  return `
You are reviewing a new video in a monitored YouTube research channel.

Channel: ${channelTitle}
Video: ${videoTitle}
Research topic: ${topic || "General"}
Output language: ${language}

Produce an evidence-based critical review from the transcript only.

Rules:
- Return at most 10 check-worthy claims, 12 signal candidates, and 5 items in every other section.
- Merge overlapping observations and omit low-value repetition.
- Keep raw claims separate from signals. A claim states something; a signal indicates a change in practice, market, tooling, roles, or user behaviour that could affect a decision.
- Exclude greetings, calls to action, future-video announcements, generic advice, and obvious historical context from check-worthy claims.
- Separate factual claims, predictions, and opinions in the claims section.
- Mark a claim as new only when it is absent from the supplied channel history.
- Report a position change only when both the earlier and current positions have explicit evidence.
- Marketing signals must identify observable persuasion or promotion, not guess intent.
- Reasoning risks may include unsupported causality, cherry-picking, missing baselines, overgeneralisation, or omitted counterarguments.
- Quality signals may identify repetition, vague language, contradictions, or confident conclusions without support.
- Never claim that content was generated by AI. Describe observable quality signals instead.
- Use canonicalTerm only when the term review status is source_backed or corrected_asr_term.
- Never expand a raw acronym marked needs_verification. Preserve it exactly and state the uncertainty.
- If a signal depends on an unverified term, do not present the terminology as established fact.
- Early signals are novel developments worth monitoring, not facts automatically treated as true.
- Do not perform external fact-checking and clearly warn when a claim needs external verification.
- Keep evidence concise and grounded in the transcript.

Signal candidate types:
- workflow_shift: a material change in how work is performed;
- role_shift: responsibility or decision-making moves between people, agents, or teams;
- tooling_opportunity: a concrete product or infrastructure gap;
- market_shift: economics, competition, distribution, or category boundaries change;
- user_behavior_shift: users adopt a meaningfully different behaviour;
- project_update: relevant only when the monitored topic tracks that project;
- historical_context: established background, normally low value;
- generic_hype: broad transformation or productivity rhetoric without a scoped baseline;
- author_metadata: announcements or personal trajectory, normally not a signal;
- recommendation: advice without evidence of broader adoption, normally low value.

For every signal candidate provide:
- what changed and where;
- why it matters;
- who is affected;
- direct evidence from the video;
- the strongest counterpoint or uncertainty;
- a concrete product opportunity, or an empty string when none exists;
- integer scores from 1 to 5 for novelty, specificity, evidence, actionability, marketImpact, and hypeRisk.

Do not call a statement a strong signal merely because it sounds ambitious. Generic statements such as "AI changes software" or unsupported productivity multipliers should be classified as generic_hype, not workflow_shift or market_shift.

Return only one JSON object with this shape:
{
  "overview": "string",
  "claims": [{ "text": "string", "kind": "factual|prediction|opinion", "confidence": "low|medium|high", "evidenceBasis": "string", "isNew": true }],
  "signals": [{ "claim": "string", "signalType": "one allowed signal type", "whyItMatters": "string", "whoIsAffected": ["string"], "evidenceFromVideo": "string", "counterpoint": "string", "productOpportunity": "string or empty", "confidence": "low|medium|high", "novelty": 1, "specificity": 1, "evidence": 1, "actionability": 1, "marketImpact": 1, "hypeRisk": 1 }],
  "positionChanges": [{ "topic": "string", "previousPosition": "string", "currentPosition": "string", "evidence": "string", "confidence": "low|medium|high" }],
  "marketingSignals": [{ "signal": "string", "evidence": "string", "severity": "low|medium|high" }],
  "reasoningRisks": [{ "signal": "string", "evidence": "string", "severity": "low|medium|high" }],
  "qualitySignals": [{ "signal": "string", "evidence": "string", "severity": "low|medium|high" }],
  "earlySignals": [{ "signal": "string", "whyItMatters": "string", "evidence": "string", "confidence": "low|medium|high" }],
  "warnings": ["string"]
}

Previous channel history:
<history>
${JSON.stringify(history)}
</history>

Pre-ranking term review:
<terms>
${JSON.stringify(terms)}
</terms>

Current transcript:
<transcript>
${transcript}
</transcript>
  `.trim();
}
